<template>
  <div>

    <div class="level px-0 mb-0 pb-0 is-mobile is-hidden-desktop">
      <nuxt-link to="/" class="level-left is-size-5">
        Company Name
      </nuxt-link>
      <div class="level-right">

        <p @click="showNav" v-if="!showMobileNav" class="is-clickable has-text-weight-semibold has-text-dark">Menu</p>
        <p @click="showNav" v-if="showMobileNav" class="is-clickable shas-text-weight-semibold has-text-dark">Close</p>
      </div>
    </div>
    <div class="mobile-nav" v-show="showMobileNav">
      <ul>
        <nuxt-link v-for="(nav, index) in navigation" :key="index" to="/"
          class="level-item has-text-weight-semibold pr-3">

          {{ nav.name }}
        </nuxt-link>

      </ul>
    </div>
    <div class="level mt-3 is-hidden-touch">
      <div class="level-left">
        <nuxt-link to="/" class="level-item  px-0 pl-1 py-0">
          Company Name </nuxt-link>

      </div>
      <div class="level-right">
        <nuxt-link v-for="(nav, index) in navigation" :key="index" to="/"
          class="level-item has-text-weight-semibold pr-3">

          {{ nav.name }}
        </nuxt-link>
      </div>
    </div>
  </div>
</template>

<script setup>

const navigation = [
  {
    'name': 'Home',
    'to': '/',
  },
  {
    'name': 'Architecture',
    'to': '/',
  },
  {
    'name': 'Bespoke',
    'to': '/',
  },
  {
    'name': 'Product',
    'to': '/',
  },
  {
    'name': 'Portraits',
    'to': '/',
  },
  {
    'name': 'Travel',
    'to': '/',
  },
  {
    'name': 'Contact',
    'to': '/',
  },
];

const showMobileNav = ref(false)

function showNav() {
  showMobileNav.value = !showMobileNav.value
}

const route = useRoute();

watch(route, value => {
  showMobileNav.value = false
}, { deep: true, immediate: true })
</script>

<style>
/* html{
  background-color:yellow;
} */

.mobile-nav {
  padding-top: 2rem;
  width: 100%;
  display: block;
}

.mobile-nav a {
  width: 100%;
  padding-top: 1rem;
  padding-bottom: 1rem;
  display: block;
  border-bottom: 1px solid #0a0a0a;
}

.is-active-radio {
  width: 10px;
  margin-right: 0.5rem;
  height: 10px;
  background-color: yellowgreen;
  border-radius: 50%;
  display: inline-block;
}

.navbar-item:hover {
  background-color: #fff;
}

/* Animate SVG pelpum Brand */

/***************************************************
 * Generated by SVG Artista on 6/30/2023, 3:08:55 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-fill-1 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 0.8s both;
  animation: animate-svg-fill-1 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 0.8s both
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-fill-2 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 0.9s both;
  animation: animate-svg-fill-2 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 0.9s both
}

@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-fill-3 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1s both;
  animation: animate-svg-fill-3 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1s both
}

@-webkit-keyframes animate-svg-fill-4 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

@keyframes animate-svg-fill-4 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

.svg-elem-4 {
  -webkit-animation: animate-svg-fill-4 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.1s both;
  animation: animate-svg-fill-4 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.1s both
}

@-webkit-keyframes animate-svg-fill-5 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

@keyframes animate-svg-fill-5 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

.svg-elem-5 {
  -webkit-animation: animate-svg-fill-5 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.2000000000000002s both;
  animation: animate-svg-fill-5 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.2000000000000002s both
}

@-webkit-keyframes animate-svg-fill-6 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

@keyframes animate-svg-fill-6 {
  0% {
    fill: transparent
  }

  100% {
    fill: rgb(150, 64, 236)
  }
}

.svg-elem-6 {
  -webkit-animation: animate-svg-fill-6 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.3s both;
  animation: animate-svg-fill-6 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.3s both
}
</style>