backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: /img
site_url: https://shinebhola.netlify.app/

collections:
  - name: 'work'
    label: 'Work'
    folder: 'content/work'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'caption', name: 'caption', widget: 'string' }
      - { label: 'tags', name: 'tag', widget: 'string' }